### ISSUE TITLE
shape script: lectura errònia label

### ISSUE THREAD

**Issue by MiquelLlunell** [GrupEstructuraElectronicaSimetria/cosymlib#5]
Sembla que al usar l'script shape no llegeix bé l'etiqueta de l'estructura de referència.

L'input (fitxer t01.xyz) és el següent:
5
ABOXIY
  N   3.9023   7.5659   14.2563
  C   3.9912   8.8145   16.4883
  S   1.0864   9.0325   13.3242
  Cl  1.4893  10.6356   16.0313
  Pt  2.7159   8.9642   15.0153

La línia de comanda:
shape -m PP-5 t01.xyz

Missatge d'error:
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/cosymlib/shape/tools.py", line 37, in get_reference_structure
    coordinates = ideal_structures[label][:-1]
KeyError: 'P'

Si en el tool.py de dins la carpeta shape afegeixo una línia 
label='PP-5'
just abans que trobi l'error, per forçar al programa a calcular amb aquesta label,
el que surt per pantalla indica que la llista de labels amb què està treballant és
de quatre elements, un per cada caràcter de la label.

Output de programa "forçat" a calcular sense aturar-se:
Structure         P          P          -          5

ABOXIY,          27.794,    27.794,    27.794,    27.794,

**Comment by efrembernuz** [comment]
Bones,

l'error esta solucionat. Si fas un update t'hauria de funcionar perfectament.

PD: Sobre el que has fet per mirar de veure l'error, igualant label='PP-5', recorda que el que li donem al shape son llistes de strings, per tant hauria de ser una llista de l'estil label=['PP-5']. De fet, l'error venia d'aquí, ja que a l'script shape no se perque no ho estavem enviant com a llist i per això et feia un loop sobre el string 'PP-5', resultant en 5 càlculs per P, P, - i 5

Efrem
