### ISSUE TITLE
Error en el symgroup

### ISSUE THREAD

**Issue by MiquelLlunell** [GrupEstructuraElectronicaSimetria/cosymlib#6]
He estat provant el grup de simetria S4 i, per als casos en que té una mesura petita dona bé (igual que symgroup
antic), però en alguns casos que ha de donar 0, dona valors molt grans, que s'assemblen molt al valor de la mesura
C4, que tampoc dona correcta en aquests casos.

Us passo un exemple que hauria de donar CSM(S4) = 0 i dona 25.4 (semblant al CSM(C4) que dona el cosym 24.4).
De fet el valor del C4 amb el symgroup antic és 15.2

Fitxer xyz:

8

 Th1        -16.80062    -0.55052   -13.74098
 Th1        -12.80008    -0.09601   -14.54017
 Th1        -15.57778     1.38797   -17.17300
 Th1        -20.18823    -1.83274   -15.67222
 Th1        -16.79762    -4.14442   -15.76983
 Th1        -12.79709    -3.68990   -16.56902
 Th1        -18.96539     0.10576   -19.10423
 Th1        -15.57478    -2.20592   -19.20184

**Comment by efrembernuz** [comment]
Bones Miquel

ja he trobat el problema. Es trobava en la cosymlib al generar la conectivitat. Per defecte, com sempre ens conve que existeixi una conectivitat ja que accelera el càlcul del symgroup, al crear una geometria la classe buscava una connectivitat, si existeix, amb uns valors per defecte. El problema no estava en la cerca d'aquesta conectivitat, sino en l'argument que es retorna quan no es troba conectivitat, ja que li deia al programa symgroup que si existia tot i retornar una llista en blanc. Això ja esta solucionat i ara em troba el valor CSM(S4) = 0, com hauria de ser. Desconec perque donava 24 i no 15, he provat diferents combinacions però no he aconseguit aquest valor de 15.2. Almenys ara dona bé que en l'antic no donava correctament.
Perque et funcioni hauries de fer dues coses:

- Actualitzar el symgroupy a la versio 0.5.7 (hi havia uns errors de escriptura en alguna variable, posava cms enlloc de csm), això recorda que era des de preferencies del pycharm.
- Fer un upgrade de la cosymlib com fas sempre

PD: en trobar aquest error he vist que hi ha un gran nombre d'elements que no tenen el radi covalent = 0.0 a la "nostra" taula periodica de la cosymlib. Potser caldria afegir tots els que es pugui, ja que en el cas del Tori si afegeixo el radi que surt a la wikipedia em genera una conectivitat que dona el valor correcte. Abel, recordes d'on van sortir els valors dels radis covalents dels altres elements? Ho dic per tenir una sola font per a tots ells.

**Comment by abelcarreras** [comment]
Crec que la connectivitat la vaig treure de dins el symgroup mateix

**Comment by abelcarreras** [comment]
els radis vull dir
