### ISSUE TITLE
Fix Permutation (Shape)

### ISSUE THREAD

**Issue by MiquelLlunell** [GrupEstructuraElectronicaSimetria/cosymlib#7]
He tornat a provar el càlcul del shape quan es fixen les permutacions (--fix_permutation) i
la mesura (que huaria de donar més gran que quan no es fixa res dóna 0.

––– FITXER INPUT ––––––––––––––––––
4
XONNOE
Si        12.73812  12.02248  32.82539
Si        12.02248  12.73812  34.67421
C         12.46423  12.56259  31.05319
C         12.56259  12.46423  36.44641
––––––––––––––––––––––––––––––––––––

––– Primera execució: shape -m SS-4 test11.xyz –––––––––––––––––––––––
Structure         SS-4

XONNOE,          30.144,
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

––– Segona execució: shape -m SS-4 --fix_permutation test11.xyz ––––––
Structure         SS-4

XONNOE,           0.000,
–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

**Comment by efrembernuz** [comment]
Bones Miquel, a primera vista crec que es un problema de l'algoritme de la part del shape en fortran. L'estructura de referencia SS-4 es correcta i el codi utilitza la subrutina cshm_fix, que es va crear fa temps per només fer la permutació que toca. Pel que he vist el que feiem era ordenar les estructures abans d'enviar-ho al shape.

A part d'això, crec que haurem de parlar en la pròxima reunió com gestionem el tema de la permutació en estructures de referencia internes de la cosymlib. Quan l'usuari dona una estructura de referència no hi ha cap problema perque l'únic que ha de fer es ordenar l'estructura de referencia com vulgui. El problema rau en que no tenim manera de que l'usuari reordeni una estructura de referencia de la cosymlib i hauriem de veure si això es necessari i si es així com fer-ho.
